// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// pictures_News ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Ipictures_NewsViewModel
    {		
        /// <summary>
        /// Gets/Sets the Pictures_NewsListControlCollection property.
        /// </summary>
		ObservableCollection<EntitiesBase.RssSearchResult> Pictures_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Selectedpictures_NewsListControlCollection property.
        /// </summary>
		EntitiesBase.RssSearchResult Selectedpictures_NewsListControlCollection { get; set; }
        
        /// <summary>
        /// Gets the Refreshpictures_NewsListControlCollectionCommand command.
        /// </summary>
		ICommand Refreshpictures_NewsListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the Getpictures_NewsListControlCollectionCommand command.
        /// </summary>
		ICommand Getpictures_NewsListControlCollectionCommand { get; }

	}
}
