// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities=WPAppStudio.Entities;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// TheStoryDataSource_Html data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class TheStory_TheStoryDataSource : ITheStory_TheStoryDataSource 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"<div class=""wysiwyg-text-align-left""><b><u>การแบ่งประเภทของสิ่งมหัศจรรย์</u></b></div><div class=""wysiwyg-text-align-left""><span> การแบ่งประเภทของสิ่งมหัศจรรย์ในโลกอันกว้างนั้นสามารถจำแนกออกเป็นหลายสาขาด้วยกัน อาทิเช่น สิ่งมหัศจรรย์สาขาภูมิศาสตร์ , สาขาประวัติศาสตร์ , สาขาจิตร<br />กรรม และสถาปัตยกรรม , สาขาชีววิทยา และก็ สาขาวิทยาศาสตร์</span></div><div class=""wysiwyg-text-align-left""><span><u><b>การจัดแบ่งสิ่งมหัศจรรย์ทางสถาปัตยกรรม</b></u></span>สามารถแบ่งได้เป็น 3 ยุค คือ</div><div class=""wysiwyg-text-align-left""><span>1. สิ่งมหัศจรรย์ของโลกยุคโบราณ<br />2. สิ่งมหัศจรรย์ของโลกยุคกลาง<br />3. สิ่งมหัศจรรย์ของโลกยุคปัจจุบัน</span></div>";
        }
	}
}

